### ISSUE TITLE
ocis in minikube doesn't work on mac

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis-charts#213]
I couldn't up ocis agains minikube on my mac M1: 

mashine: Apple M1, macOc ventura 13.2
docs: https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes-and-helm

due this issue
`kubectl logs proxy-5fd566d54-kg49r`
log: 
`{"level":"error","service":"proxy","error":"Get \"https://ocis.kube.owncloud.test/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","time":"2023-04-25T10:35:49.396837462Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/oidc_auth.go:230","message":"could not initialize oidcAuth provider"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"d1ae5af1-e7b8-40bc-924b-2a40919223f5","remote-addr":"10.244.0.1","method":"POST","status":401,"path":"/api/v0/settings/values-list","duration":10001.714254,"bytes":0,"time":"2023-04-25T10:35:49.397320171Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}`

![image](https://user-images.githubusercontent.com/84779829/234257703-177d3682-a362-4c91-b01d-1dc76a4c8818.png)

cc @rhafer

**Comment by d7oc** [comment]
@ScharfViktor Please also trying pinging `ocis.kube.owncloud.test` in the pod. I'm curious about the IP it is resolved to.

**Comment by ScharfViktor** [comment]
> ocis.kube.owncloud.test

![image](https://user-images.githubusercontent.com/84779829/234276178-714d232d-6af0-45cf-8755-381eab6ed901.png)

**Comment by d7oc** [comment]
And `192.168.179.3` is the IP of the en0 interface of your Mac, right?

**Comment by rhafer** [comment]
> And `192.168.179.3` is the IP of the en0 interface of your Mac, right?

Actually it was a different IP. But when I looked at @ScharfViktor 's setup, the pod was able to resolve the hostname to the correct IP (the one of the en0 interface). It was not able to connect to that it. So e.g.

`curl -v https://ocis.kube.owncloud.test/.well-known/openid-configuration` from within the pod did resolve the correct IP but just hung trying to open a connection. (It worked when running the command from the host). So something in this setup on MacOS is preventing to connect to the en0 ip from within the pods. What ever that is.

**Comment by d7oc** [comment]
Strange this was working in the Minikube test I did some time back then. I just have an Intel-based Mac, no M1. MacOS also has an internal Firewall, maybe you could deactivate this temporarily or add an exception. That might be a difference as I have deactivated it here as my system is in a single computer network with a firewall upfront.

**Comment by wkloucek** [comment]
We will update documentation on how to run oCIS in Minikube on MacOS

**Comment by wkloucek** [comment]
solved in https://github.com/owncloud/docs-ocis/pull/621
