### ISSUE TITLE
expose CORS `allow_origins` configuration

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#244]
We should expose CORS `allow_origins` settings.

The current default for oCIS is:
```
http:
  cors:
    allow_origins:
    - '*'
```

By exposin a configuration for that, admins can narrow that down for security purposes.

I don't see a usecase for exposing `allow_methods`, `allow_headers` and `allow_credentials`, too. But if somebody has one, please speak up or we also can add it later.

**Comment by ainmosni** [comment]
This is a bit unclear, where do you want this defined? Isn't this already possible with custom ingress annotations? Or do you want a more "simple" way to add those annotations?

**Comment by ainmosni** [comment]
Ah that makes more sense, I missed those settings.
