### ISSUE TITLE
Some environment/helm variables mismatched with latest version of OCIS

### ISSUE THREAD

**Issue by bennycooly** [owncloud/ocis-charts#289]
I was taking a look at why the Graph service was failing to start, and found a couple of mismatched environment vars:
- `OCIS_LDAP_BIND_PASSWORD` is set by [the helm chart](https://github.com/owncloud/ocis-charts/blob/master/charts/ocis/templates/graph/deployment.yaml#L71) but on latest this variable has [not been added yet](https://github.com/owncloud/ocis/blob/master/services/graph/pkg/config/config.go#L53)
- `GRAPH_LDAP_USER_DISPLAYNAME_ATTRIBUTE` is set to `.Values.features.externalUserManagement.ldap.user.displayName` but there is no value for this in the helm chart; should it be `...ldap.user.schema.displayName`?

**Comment by Excds** [comment]
PR #287 has been merged.
