### ISSUE TITLE
NodeSelector ?

### ISSUE THREAD

**Issue by remixmabix** [owncloud/ocis-charts#335]
I have just installed the project a few minutes ago and can't see where I can define the node selector for the platform arm64v8, 

It seems (if I understand well) that the template image is a busybox one for all the pods ?

How can I approch this ? 

Though it works well by the loto of assignment now on my raspberry pi 4, I can log in with no issues but it might not be the case after a reboot.

Thanks.

**Comment by remixmabix** [comment]
Managed myself to pass an, argument in the helm install chart : 

helm install ocis ./charts/ocis --namespace ocis --create-namespace \
	--set nodeSelector."beta\\.kubernetes\\.io/arch"=arm64

Kind Regards

**Comment by remixmabix** [comment]
@wkloucek Ok it's more clean in my head about how it works about busybox and InitContainers method.

True, I was referencing to kubernetes.io/arch

Thanks for the #336 ticket

Best Regards.

**Comment by wkloucek** [comment]
tracked in #336, started working on it in #385
