### ISSUE TITLE
Overly pessimistic supported kubeVersions

### ISSUE THREAD

**Issue by Deaddy** [owncloud/ocis-charts#338]
The Chart.yaml contains the overly paran^h^h^h^hessimistic assumption:
```
# should only contain non EOL versions from https://kubernetes.io/releases/patch-releases/#non-active-branch-history
# if this changes, also kubernetesVersions in .drone.star needs to be changed
```

The supported kubernetes version in the `Chart.yml` should be dependend on and only dependend on the apiVersions used throughout the helm chart; a grep yields these:

- `v1`
- `apps/v1`
- `batch/v1`
- `monitoring.coreos.com/v1`
- `networking.k8s.io/v1`
- `policy/v1`
- `rbac.authorization.k8s.io/v1`

With `monitoring.coreos.com/v1` being a Prometheus Operator CRD, this should work out to 1.19 as minimal version, see also https://kubernetes.io/docs/reference/using-api/deprecation-guide/

If there are issues making it not work despite the compatible API, this is a bug (in k8s or whatever component is producing the issue) and these should be explicitely noted in the `Chart.yml` to clarify this restriction.

Tested versions and soft-support (e.g. what the devs are willing and able to support, not what technically is supported) should also be a soft requirement, i.e. documented in `README.md`, e.g. just a sentence such as
"We can only support non-EOL kubernetes versions, see also https://kubernetes.io/releases/patch-releases/#non-active-branch-history)"

Then this documentation, not `Chart.yml` is kept in sync with `.drone.star`. One could also think of a compability matrix which tracks both test coverage and apiVersion compability, e.g.

| k8s version | covered by test | supported by devs | api compatible |
| - | - | -| - |
| 1.19 - 1.23 | no | no | yes |
| 1.24 - 1.26 | yes | no | yes |
| 1.27 | yes | yes | yes |

Non-tiny production clusters move a bit slower through the whole update space as there are hundreds of components to be kept working together, which can take significant time, especially when other vendors lag behind with API deprecations, so at some point it will be necessary to broaden the range of supported k8s versions.

**Comment by wkloucek** [comment]
@Deaddy could you please leave comments on PR #392
