### ISSUE TITLE
use service accounts on `next` branch

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#390]
when service accounts arrived in oCIS we should use them on a `next` branch of this Helm Chart for:
- trashbin cleanup job
- proxy

This needs at least the new "auth-service" (https://github.com/owncloud/ocis/tree/master/services/auth-service)

**Comment by wkloucek** [comment]
@kobergj do you already have information / documentation about how to use the service accounts feature for the trashbin cleanup job? 

Do I need to set `STORAGE_USERS_PURGE_TRASH_BIN_USER_ID` to some special ID ?  https://github.com/owncloud/ocis/tree/master/services/auth-service mentions only `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET`

**Comment by wkloucek** [comment]
Proxy for oCIS `latest` needs it: https://github.com/owncloud/ocis/pull/7240/files#diff-d4152e936556fd4b52296d3d6bab0aad4cbb24107c03224c1a9a2383a450f7e4

**Comment by wkloucek** [comment]
> `storage-users` service needs `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET` set. (or `ocis init` needs to be run on a fresh system)

And `STORAGE_USERS_PURGE_TRASH_BIN_USER_ID` should be left empty? Because that one still exists

**Comment by kobergj** [comment]
Yes not needed any more. I'll remove it

**Comment by wkloucek** [comment]
Switch to service auth was done in #401 but `STORAGE_USERS_PURGE_TRASH_BIN_USER_ID` is still used

**Comment by kobergj** [comment]
Good find :+1: Fix here: https://github.com/owncloud/ocis-charts/pull/405

**Comment by wkloucek** [comment]
https://github.com/owncloud/ocis-charts/pull/405 was merged
