### ISSUE TITLE
support `SETTINGS_DEFAULT_LANGUAGE`

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#404]
support setting `SETTINGS_DEFAULT_LANGUAGE`

Needs to go to `next` as of now.

**Comment by wkloucek** [comment]
Needs to be adapted to https://github.com/owncloud/ocis/issues/7465#issuecomment-1765911050

**Comment by case0sh** [comment]
fixed https://github.com/owncloud/ocis-charts/pull/408
