### ISSUE TITLE
Add renovate bot support to repo

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#429]
Currently this repo has no renovate bot support. It could make sense to add this here to automatically update to new docker image version etc. See also https://github.com/owncloud-docker/helm-charts/pull/60.

@wkloucek Opinions?

**Comment by wkloucek** [comment]
Yes please! :pray:

**Comment by wkloucek** [comment]
_Originally posted by @d7oc in https://github.com/owncloud/ocis-charts/issues/437#issuecomment-1830164020_

> @d7oc somehow the renovate comment also doesn't work. But I didn't have time to investigate

Comment? Which comment?

https://github.com/owncloud/ocis-charts/blob/d73fe65204ebf14e888bdfcb996ee9660d4a5a5b/charts/ocis/Chart.yaml#L13-L14

**Comment by d7oc** [comment]
Ah. I take a short look

**Comment by d7oc** [comment]
https://github.com/owncloud/ocis-charts/pull/438 should fix this. Unfortunately we'll only see that this is finally working after it's merged to master.

**Comment by wkloucek** [comment]
![image](https://github.com/owncloud/ocis-charts/assets/34452982/931f3e40-3888-47ec-813c-571b420a94aa)

Looks good now

**Comment by wkloucek** [comment]
@d7oc are we done here?

**Comment by d7oc** [comment]
Yes from my side it's done. Closing it.
