### ISSUE TITLE
Add web concurrent share requests config

### ISSUE THREAD

**Issue by micbar** [owncloud/ocis-charts#473]
# Description

As of ocis 5.0.0, web has a new setting which intends to reduce concurrency in sharing requests on very slow NFS storages.

Ocis PR: https://github.com/owncloud/ocis/pull/8056
Web Ticket: https://github.com/owncloud/web/issues/10227

@kulmann @JammingBen May I ask you to take care of that and assign one of you to that ticket?

**Comment by micbar** [comment]
@wkloucek @d7oc FYI

**Comment by wkloucek** [comment]
Relevant settings: https://github.com/owncloud/ocis/pull/8056/files#diff-49a11f9b07aa943e0d54761d91355bc0e2c2d74e3e83789f68ce0b8418ec65e0R84-R95

**Comment by JammingBen** [comment]
I didn't find any time for this yesterday, but I can check now. I'll drop you a message if I need help from a backend engineer.

**Comment by wkloucek** [comment]
Guess it's done, but will only work properly with some release after oCIS 5.0.0-rc.3
