### ISSUE TITLE
Add possibility to specify the image parameters per service 

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#475]
In some environments requirements exist to specify different images for different services. Right now the charts only use one for all. This should be changed so this can be specified (overwritten) per service similar to other configurations like `resources` or `podDisruptionBudget`.

**Comment by dj4oC** [comment]
What are the downsides?

**Comment by wkloucek** [comment]
> What are the downsides?

- more config options (= could serve as footgun :laughing:)
- If you don't know what you're doing you can break stuff, but that's already the case since the chart is only working with specific oCIS version (better leave the image tag untouched / stick to appVersion of the chart)
