### ISSUE TITLE
INSTALLATION FAILED with 5.0.0_rc-2

### ISSUE THREAD

**Issue by dj4oC** [owncloud/ocis-charts#476]
Using the helm chart to deploy 5.0.0_rc-2 leads to the following error message. Any idea why?

`Error: INSTALLATION FAILED: template: ocis/templates/webfinger/service.yaml:1:4: executing "ocis/templates/webfinger/service.yaml" at <include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameWebfinger" "appNameSuffix" "")>: error calling include: template: ocis/templates/_common/_tplvalues.tpl:84:107: executing "ocis.basicServiceTemplates" at <.scope.appSpecificConfig.priorityClassName>: nil pointer evaluating interface {}.priorityClassName`

**Comment by wkloucek** [comment]
which Helm Chart version?

**Comment by dj4oC** [comment]
next branch

**Comment by wkloucek** [comment]
> next branch

`next` is not a real version. Do you have a commit id? The velocity on this branch is sometimes quite high and the changes really disruptive.

**Comment by wkloucek** [comment]
Closing because stale since 2 weeks
