### ISSUE TITLE
built-in admin doesn't work on fresh install?

### ISSUE THREAD

**Issue by mhegreberg** [owncloud/ocis-charts#486]
I'm evaluating owncloud for my org, and when I run this chart I get the following error trying to sign into the 'admin" account:
![image](https://github.com/owncloud/ocis-charts/assets/11844475/60142d7e-0538-478a-947a-3ad3b75cf431)
this is with a pretty untouched values.yaml. I just setup the ingress and nothing else.

am I missing something with deploying this? all the pods seem to be online, and I'm not seeing any errors in the logs for the pods that would seem to have to do with authentication

**Comment by wkloucek** [comment]
> this is with a pretty untouched values.yaml. I just setup the ingress and nothing else.
> 
> am I missing something with deploying this? all the pods seem to be online, and I'm not seeing any errors in the logs for the pods that would seem to have to do with authentication

You need to make sure that the domain you're using is also resolvable in the oCIS pods.

For a test environment with Minikube we have some configuration hints: https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#start-minikube . On other systems you could just use the `hostAliases` option (https://github.com/owncloud/ocis-charts/blob/96fa3164b7d0be9d6553c9a4d4d210373388ce78/charts/ocis/values.yaml#L140-L144).

If DNS resolving is just working fine, I'd be interested in some proxy pod logs.

**Comment by mhegreberg** [comment]
Thank you! this is exactly what I needed. I missed that in the docs.

I also had to set 
```
insecure:
  oidcIdpInsecure: true
  ocisHttpApiInsecure: true
```

because this is just a test install, and I havent bothered to issue a cert.
