### ISSUE TITLE
Frontend: core access token not set

### ISSUE THREAD

**Issue by manbari** [owncloud/ocis-charts#494]
Hello, 

I will appreciate your support on the following matter.
I have installed OCIS in a local Kubernetes cluster based on the instructions on https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes-and-helm. 

It has been successfully deployed but when I try to access the frontend component at http://localhost:9140 (I have used port forward) I receive 401 Unauthorized exceptions.

The respective logs are the following. Is there any further configuration needed?

{"level":"warn","service":"frontend","pkg":"rhttp","traceid":"6a256b236933608ad4f74b63bd760cfb","time":"2024-03-05T10:17:57.869500155Z","line":"github.com/cs3org/reva/v2@v2.16.4-0.2023 1220070538-82b93f6a66bc/internal/http/interceptors/auth/auth.go:230","message":"core access token not set"}             
                                                                 {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"6a256b236933608ad4f74b63bd760cfb","host":"127.0.0.1","method":"GET","uri":"/","url":"/","proto":"HTTP/1.1","status":401,"size":0,"start":"05/Mar/2024:10:17:57 +0000","end":"05/Mar/2024:10:17:57 +0000","time_ns":7255220,"time":"2024-03-05T10:17:57.869585162Z","line":"github.com/cs3org/reva/v2@v2.16.4-0.202 31220070538-82b93f6a66bc/internal/http/interceptors/log/log.go:112","message":"http"}     
                                                                 
                                                                 
   Thank you very much

**Comment by wkloucek** [comment]
The "frontend" service / deployment / pods don't provide a "web frontend". 

You need to go via the proxy service port 9200 or set up a ingress.
