### ISSUE TITLE
make it easier to set up secrets

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#50]
creating secrets for the oCIS chart is a manual process currently. We should aim at making this easier.

**Comment by remram44** [comment]
Generating them from Helm, reading the old value via `lookup`, is limited. It will only work for what you can generate from Helm, e.g. random strings, not keys. In addition it won't work when using `helm template` because `lookup` will return null.

Another option is to create a Job that talks to the Kubernetes API via a service account to check the secret and possibly generate them. This will work with `helm template` and allows you to run any code you want (in the Job's container). You can also make it a `post-install,post-upgrade` [chart hook](https://helm.sh/docs/topics/charts_hooks/) to have it run first and re-run on updates.

**Comment by remram44** [comment]
Either way I think blaming Helm in your docs is inappropriate and should be removed. You are using Helm incorrectly and blaming them, and it's a bad look.

https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html

> Helm does not support one-off generation of secrets out of the box. Certificates are also required which should expire and therefore need a certificate rotation from time to time, which is also not supported by Helm

> Helm does not support one-off generation of configuration out of the box

> Certificates are also required which should have an expiration date and therefore need a certificate rotation from time to time, which is also not supported by Helm

> Certificates are also required which should expire and therefore need a certificate rotation from time to time, which is also not supported by Helm

All of this is supported by Helm. You just haven't written the Jobs and CronJobs that are the way to do it and works for everyone else.

**Comment by remram44** [comment]
If you don't actually rotate certificates, it looks like Helm might have all you need built-in , e.g. with [genCA](https://helm.sh/docs/chart_template_guide/function_list/#genca)/[genSelfSignedCert](https://helm.sh/docs/chart_template_guide/function_list/#genselfsignedcert)/[genSignedCert](https://helm.sh/docs/chart_template_guide/function_list/#gensignedcert)

Here are a few I could find, I hope that helps:

* GitLab's shared secrets: [job template](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/templates/shared-secrets/job.yaml), [script template](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/templates/shared-secrets/_generate_secrets.sh.tpl) (it's a shell script that calls kubectl and openssl), [rbac](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/templates/shared-secrets/rbac-config.yaml)
* GitLab's nginx secrets: [job template](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml), [role](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/nginx-ingress/templates/admission-webhooks/job-patch/role.yaml), [rolebinding](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/nginx-ingress/templates/admission-webhooks/job-patch/rolebinding.yaml)
* Bitnami's Contour chart: [job template](https://github.com/bitnami/charts/blob/main/bitnami/contour/templates/certgen/job.yaml), [rbac](https://github.com/bitnami/charts/blob/main/bitnami/contour/templates/certgen/rbac.yaml) (Bitnami seems to be using mostly `lookup` and `initContainers`)
