### ISSUE TITLE
Support LDAP autoprovisioning in helm chart

### ISSUE THREAD

**Issue by eforest** [owncloud/ocis-charts#522]
Support LDAP autoprovisioning in helm chart

All that is missing is an environment variable for "proxy" in https://github.com/owncloud/ocis-charts/blob/main/charts/ocis/templates/proxy/deployment.yaml like this:

`
            - name: PROXY_AUTOPROVISION_ACCOUNTS
              value: {{ .Values.features.externalUserManagement.autoprovisionAccounts | default "false" | quote }}
`

and a boolean flag autoprovisionAccounts in externalUserManagement section of values files.

This can be useful in scenarios where you have an OIDC Idp which is not backed by LDAP but some other user store.
In this case we want OCIS to autoprovision users in its external LDAP (which is used for OCIS exclusively).

**Comment by wkloucek** [comment]
Hi @eforest, thanks for this issue and your PR! I added the documentation part on the PR and asked a colleague for review.

Sorry that our feedback took that long.
