### ISSUE TITLE
ArgoCD - keycloak Failed to clone

### ISSUE THREAD

**Issue by camrossi** [owncloud/ocis-charts#546]
I have tried to deploy the new chart from main that supports ocis 5.0.2 and with argo was failing as the .gitmodules reference 
`url = git@github.com:keycloak/keycloak-k8s-resources.git` 

and when argo executes ` git submodule update --init --recursive` it fails with 
```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

As a workaround I just forked the repo and changed the url to `https://github.com/keycloak/keycloak-k8s-resources.git` and now I have upgraded from 4.0.7 to 5.0.2 without any issues.

**Comment by wkloucek** [comment]
Cloning via ssh only works if ssh is set up. Therefore https urls for the submodules are preferable.
