### ISSUE TITLE
Thumbnails hardening

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#570]
expose `THUMBNAILS_MAX_CONCURRENT_REQUESTS` and `THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE` as a configuration when available

**Comment by wkloucek** [comment]
Was also back ported to stable-5.0 -> https://github.com/owncloud/ocis/pull/9252

**Comment by wkloucek** [comment]
@dschmidt is this something you could have a look at, too?

**Comment by dschmidt** [comment]
If it's just adding those settings to the thumbnails service, I can probably manage to do that, yeah

**Comment by wkloucek** [comment]
@d7oc During https://github.com/owncloud/ocis-charts/pull/654, I looked at it and oCIS 5.0.6 supports now `THUMBNAILS_MAX_CONCURRENT_REQUESTS` but not `THUMBNAILS_MAX_INPUT_IMAGE_FILE_SIZE`, so we could only port half of https://github.com/owncloud/ocis-charts/pull/642. Should I do it anyways?

**Comment by d7oc** [comment]
Better some protection than nothing I would say.
