### ISSUE TITLE
.Values.features.emailNotifications.smtp.authentication "auto"

### ISSUE THREAD

**Issue by ClaudiuLSH** [owncloud/ocis-charts#585]
Isn't [this](https://github.com/owncloud/ocis-charts/blob/main/charts/ocis/templates/notifications/deployment.yaml#L67) supposed to be set none instead of auto?

If set to none it should not create those env variables but right now if set to none in values it throws an error. Or am I missing something?

**Comment by wkloucek** [comment]
On the first look, that actually looks like a bug. Probably `auto` should be replaced by `none` here? :thinking:  

I need to look into it in detail.
