### ISSUE TITLE
oCIS 6 support

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#632]
The following features of oCIS 6 need to be added in the chart (currently this should be place on `next` branch).

- [x] add collaboration service (https://github.com/owncloud/ocis-charts/pull/567 / https://github.com/owncloud/ocis-charts/issues/545)
- [x] https://github.com/owncloud/ocis-charts/issues/569
- [x] https://github.com/owncloud/ocis-charts/issues/570
- [ ] #649
- [x] https://github.com/owncloud/ocis-charts/pull/633 (6.1)
- [x] https://github.com/owncloud/ocis-charts/issues/652

Backref note: OCSRE-220

**Comment by d7oc** [comment]
@wkloucek Anything missing from the enumeration we did yesterday?

**Comment by wkloucek** [comment]
There is now a `stable-5` branch where the oCIS 5 compatible chart will be continued to be maintained.

oCIS rolling (6.1) changes can go to `main` now.

**Comment by wkloucek** [comment]
We should also have a look into https://github.com/owncloud/ocis-charts/issues/643

**Comment by wkloucek** [comment]
I'm closing here because the only open item is https://github.com/owncloud/ocis-charts/issues/649 for which we already have the PR https://github.com/owncloud/ocis-charts/pull/701
