### ISSUE TITLE
OpenShift Route support

### ISSUE THREAD

**Issue by case0sh** [owncloud/ocis-charts#652]
oCIS 6 supports OpenShift Route configurations . The chart support for this feature should be added within this issue.

**Comment by d7oc** [comment]
Just adding the comment here. Currently there is some investigation whether include support or just add documentation. Test of possible documentation currently outstanding, afterwards we will change the `README.md` to add those descriptions.

cc @wkloucek @case0sh

**Comment by wkloucek** [comment]
From what I remember, we'll not gonna add routes to the oCIS chart. They can be included via https://github.com/owncloud/ocis-charts/blob/c6ef3d2de98ec5caccf00f367a42047e931e0596/charts/ocis/values.yaml#L845-L847
