### ISSUE TITLE
external user deployment example schema adaptions

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#717]
see https://github.com/owncloud/ocis/pull/9942

**Comment by wkloucek** [comment]
We'll probably need for oCIS 6.4.0 for it to be released

**Comment by wkloucek** [comment]
Will be done by https://github.com/owncloud/ocis-charts/issues/717

**Comment by d7oc** [comment]
> Will be done by #717

self-reference?

**Comment by wkloucek** [comment]
Done in https://github.com/owncloud/ocis-charts/pull/759
