### ISSUE TITLE
allow configuring GRAPH_AVAILABLE_ROLES

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#738]

**Comment by wkloucek** [comment]
This is not part of oCIS rolling 6.3.0 -> needs to wait until 6.4.0 release

**Comment by d7oc** [comment]
Documentation to be found in https://owncloud.dev/services/graph/

**Comment by wkloucek** [comment]
> Documentation to be found in https://owncloud.dev/services/graph/

I didn't find anything in the Web UI though, where I could choose. Maybe I didn't get yet what it's all about
