### ISSUE TITLE
expose `FRONTEND_MAX_CONCURRENCY` configuration

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#791]
expose `FRONTEND_MAX_CONCURRENCY` config option when a oCIS version is released that exposes it, see also https://github.com/owncloud/ocis/pull/10476

**Comment by mmattel** [comment]
@wkloucek maybe you should use `OCIS_MAX_CONCURRENCY` which addresses this on a global basis. See: https://github.com/owncloud/ocis/pull/10476 and https://github.com/owncloud/ocis/pull/10483

**Comment by wkloucek** [comment]
oCIS charts is using the most scoped env var because the `OCIS_xxx` variables are often overloaded. Eg. `OCIS_URL` basically configures where oCIS is reachable and where the IDP is reachable. Which only works, if you have the builtin IDP.

**Comment by wkloucek** [comment]
Please also note that the oCIS chart and oCIS single-process setup share basically no common concept when it comes to configuration. Therefore this `OCIS_xxx` concept is just not applicable.
